In [ ]:
from sklearn import datasets
from sklearn.metrics import confusion_matrix

import numpy as np

iris = datasets.load_iris()
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris.data, iris.target, test_size = 0.2)


In [22]:
clf = LinearRegression()
clf.fit(X_train,Y_train)
Y_pred = clf.predict(X_test).astype(int)
print(confusion_matrix(Y_test, Y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  7  4]]


In [24]:
from sklearn.metrics import classification_report
print(classification_report(Y_test, Y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       0.56      1.00      0.72         9
          2       1.00      0.36      0.53        11

avg / total       0.87      0.77      0.74        30



In [27]:
from sklearn.model_selection import cross_val_score
clf2 = LinearRegression()
cross_val_score(clf2, iris.data, iris.target, cv=5)

array([ 0.        ,  0.85215955,  0.        ,  0.76225759,  0.        ])

## Logistic Regression
1. How to find complex functions using linear regression. Added X^2 etc features
2. Why is Linear Regression bad for classification?
3. Logistic Regression:
    1. Sigmoid function
    2. Plot of sigmoid function
    3. How to get to the decision boundary from the sigmoid function
    4. Cost Function
    5. Derivative of cost function and gradient Descent
    6. Multiclass classification
    7. Regularization