In [1]:
import numpy as np

In [153]:
a1 = np.array([1,2,3])
a2 = np.array([2,2,3])

In [132]:
numerator = (a1*a2).sum() + (a1.sum())*(a2.sum())
denominator = (a1**2).sum() + (a1.sum()**2)
m = numerator/denominator
m

1.1399999999999999

In [115]:
slope = m*a1.sum() - a2.sum()
slope

-0.16000000000000014

In [11]:
def fitFunct(X_train , Y_train):
    a = X_train
    b = Y_train
    numerator = (a*b).sum() - (a.sum())*(b.sum())
    denominator = (a**2).sum() - (a.sum()**2)
    m = numerator/denominator
    slope = b.sum() - m*a.sum() 
    return (m,slope)

In [149]:
m,b = fitFunct(a1,a2)
print(m)
print(b)

1.22727272727
-0.363636363636


In [12]:
def predict(m,b,X_test):
    Y_predict = (X_test*m) + b
    return Y_predict

In [158]:
X_test = np.array([1,2,3])
Y_test = np.array([1,3,5])

Y_predict = predict(m,b,X_test)
print(Y_predict)

[ 0.86363636  2.09090909  3.31818182]


In [13]:
def score(Y_predict,Y_test):
    Y_mean = Y_test.mean()
    num = ((Y_predict - Y_test)**2).sum()
    den = ((Y_predict - Y_mean)**2).sum()
    result = 1 - (num/den)
    return result

In [160]:
score(Y_predict,Y_test)

0.33107599699021806

In [2]:
from sklearn import datasets
import pandas as pd

In [3]:
iris = datasets.load_iris()

In [4]:
df = pd.DataFrame(iris.data)

In [5]:
df.columns = iris.feature_names
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.054000           3.758667   
std             0.828066          0.433594           1.764420   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.198667  
std            0.763161  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [6]:
from sklearn import cross_validation as cv

/home/rattandeep/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
X_train , X_test , Y_train , Y_test = cv.train_test_split(df , iris.target , test_size = 0.2)

In [99]:
X_train_mat = X_train.as_matrix(columns = ['petal width (cm)'])
#Y_train_mat = Y_train.as_matrix(columns = ['sepal length (cm)'])
X_test_mat = X_test.as_matrix(columns = ['petal width (cm)'])
#Y_test_mat = Y_test.as_matrix(columns = ['sepal length (cm)'])

In [100]:
Y_train = Y_train.reshape((120,1))
Y_test = Y_test.reshape((30,1))
print(X_train_mat.shape)
print(Y_train.shape)
print(X_train_mat)
print(Y_train)

(120, 1)
(120, 1)
[[ 1.4]
 [ 2.5]
 [ 2.3]
 [ 0.2]
 [ 1.4]
 [ 1.5]
 [ 1.3]
 [ 1.7]
 [ 0.4]
 [ 0.6]
 [ 1.4]
 [ 2. ]
 [ 1.5]
 [ 2.3]
 [ 1.3]
 [ 2.1]
 [ 1.4]
 [ 2. ]
 [ 1. ]
 [ 0.1]
 [ 0.4]
 [ 0.2]
 [ 1.4]
 [ 1. ]
 [ 1.8]
 [ 1.3]
 [ 1. ]
 [ 0.2]
 [ 1.3]
 [ 1.6]
 [ 0.2]
 [ 1.5]
 [ 1.8]
 [ 0.2]
 [ 2.3]
 [ 1.6]
 [ 0.3]
 [ 1.2]
 [ 0.2]
 [ 0.2]
 [ 1.8]
 [ 0.1]
 [ 0.2]
 [ 0.2]
 [ 1.5]
 [ 2. ]
 [ 2.3]
 [ 1.5]
 [ 2.1]
 [ 1.8]
 [ 1. ]
 [ 1. ]
 [ 1.5]
 [ 1.4]
 [ 0.2]
 [ 1.2]
 [ 0.5]
 [ 1.8]
 [ 2.4]
 [ 1.8]
 [ 1.1]
 [ 2.4]
 [ 2.1]
 [ 0.2]
 [ 1.1]
 [ 1.9]
 [ 1.2]
 [ 0.3]
 [ 1.5]
 [ 2.5]
 [ 0.2]
 [ 1.3]
 [ 1.3]
 [ 1.2]
 [ 1.3]
 [ 0.1]
 [ 2.5]
 [ 1.9]
 [ 0.2]
 [ 0.1]
 [ 0.2]
 [ 0.2]
 [ 1.4]
 [ 0.2]
 [ 1.8]
 [ 1.5]
 [ 0.4]
 [ 0.2]
 [ 0.2]
 [ 1.5]
 [ 2. ]
 [ 0.2]
 [ 1.5]
 [ 0.4]
 [ 0.2]
 [ 2.4]
 [ 1.6]
 [ 0.2]
 [ 1.2]
 [ 0.3]
 [ 1.4]
 [ 0.3]
 [ 1.9]
 [ 1.3]
 [ 1.9]
 [ 0.2]
 [ 2.3]
 [ 0.2]
 [ 1. ]
 [ 0.1]
 [ 0.2]
 [ 1.7]
 [ 2.1]
 [ 0.4]
 [ 2.3]
 [ 0.4]
 [ 2.2]
 [ 1.8]
 [ 2.2]
 [ 0.2]]
[[2]
 [2]
 [2]
 [0]
 

In [101]:
m,b = fitFunct(X_train_mat,Y_train)
print(m)
print(b)

0.817819394372
0.0963750907458


In [102]:
Y_predict = predict(m,b,X_test_mat)

In [103]:
print(score(Y_predict,Y_test))

0.755336826323
