In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn import cross_validation as cv
from sklearn import datasets

/home/rattandeep/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [99]:
boston = np.genfromtxt("https://ninjasprodml.s3.amazonaws.com/0000000000002417_training_boston_x_y_train.csv?AWSAccessKeyId=AKIAIGEP3IQJKTNSRVMQ&Expires=1521168759&Signature=b5eAP8PbNLIiEcjOAPjmsDOor78%3D",delimiter = ",")
X_test = np.genfromtxt("https://ninjasprodml.s3.amazonaws.com/0000000000002417_test_boston_x_test.csv?AWSAccessKeyId=AKIAIGEP3IQJKTNSRVMQ&Expires=1521168901&Signature=%2B7XX6QKjdclG%2FDD4MdjA%2BOwTr3o%3D",delimiter = ",")

In [86]:
X_train = boston[:,:13]
Y_train = boston[:,13]

In [87]:
ones = np.ones((379,1))
X_train = np.append(X_train, ones, axis=1)

In [88]:
X_train.shape

(379, 14)

In [89]:
X_train

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011,  1.        ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412,  1.        ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588,  1.        ],
       ..., 
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299,  1.        ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218,  1.        ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335,  1.        ]])

In [100]:
ones = np.ones((127,1))
X_test = np.append(X_test, ones, axis=1)

In [91]:
# Feature Scaling

mean = np.sum(X_train, axis=0)

rangee = np.amax(X_train, axis=0) - np.amin(X_train, axis=0)

print(mean)
print("------------------")
print(rangee.shape)

for i in range(13):
    X_train[:,i] = (X_train[:,i] - mean[i])/rangee[i]
    
print(X_train)

    #    mean = matrix[:,j].mean()
    #    rangee = matrix[:,j].max() - matrix[:,j].min()
    #    for i in range(N):
    #        if(rangee!=0):
    #            matrix[i,j] = (matrix[i,j] - mean)/rangee
    #        else:
    #            matrix[i,j] = (matrix[i,j] - mean)

[   7.43902903    0.93057556   13.70831272   10.97403844   10.90565444
   12.20443435   14.55182892   -0.48828906   16.41342955   16.59506066
    7.28348785   -5.98235129    6.98051873  379.        ]
------------------
(14,)
[[-0.75746108 -0.33045485 -3.80102473 ...,  1.47843189 -1.63495306  1.        ]
 [-0.75741511 -0.33045485 -3.41695065 ...,  1.45081893 -1.51807363  1.        ]
 [-0.70600771 -0.33045485 -3.22176547 ...,  0.50566451 -1.23239987  1.        ]
 ..., 
 [-0.75750559 -0.33045485 -3.41695065 ...,  1.46027681 -1.48034313  1.        ]
 [-0.75772847 -0.33045485 -3.77213584 ...,  1.43048321 -1.5634637   1.        ]
 [-0.68499015 -0.33045485 -3.22176547 ...,  1.47318315 -1.68771902  1.        ]]


In [92]:
def step_gradient(X_train, Y_train, learning_rate, current_coeff):
    
    temp = np.dot(X_train, current_coeff)
    
    value = Y_train - temp
    
    coeff_slope = np.dot(X_train.T, value)
    
    coeff_slope = -(2/379) * coeff_slope
    
    new_coeff = current_coeff - learning_rate * coeff_slope
    
    #print(current_coeff.shape)
    #value = Y_train - np.sum(temp,axis=1)
    
    #N = len(X_train)
    
    #print(value.shape)
    #value = np.reshape(value,(1,379))
    #print(value.shape)

    
    #coeff_slope = -(2/N) * value * X_train
    #print(coeff_slope.shape)
    #print(coeff_slope)
    
    
    #N = len(matrix)
    #M = len(current_coeff)
    #coeff_slope = [0 for i in range(M)]
    #new_coeff = []
    
    #for i in range(N):
        
     #   x = matrix[:,:14]
     #   y = matrix[i,14]
        
     #   value = y 
        
     #   for j in range(M):
     #       value = value - current_coeff[j]*x[i][j]
     #   for j in range(M):
     #       coeff_slope[j] += -(2/N) * value * matrix[i][j]
     #   # b_slope += -(2/N) * (y - m_current*x - b_current)
     #   # m_slope += -(2/N) * (y - m_current*x - b_current) * x
    
    #for i in range(M):
    #    new_coeff.append(current_coeff[i] - learning_rate*coeff_slope[i])
    return new_coeff

In [93]:
def cost_gd(coeff, X_train, Y_train):
    
    temp = np.dot(X_train, coeff)
    
    value = Y_train - temp
    
    value = value**2
    
    total_cost = (np.sum(value)) / 379
    
    #M = len(coeff)
    #total_cost = 0
    
    #for i in range(len(matrix)):
    #    x = matrix[:,:14]
    #    y = matrix[i,14]
    #    
    #    value = y 
    #    for j in range(M):
    #        value = value - coeff[j]*x[i][j]
        
    #    total_cost += value**2
      
    return total_cost

In [94]:
def gd_runner(X_train, Y_train, learning_rate, num_iterations):
    
    coeff = np.zeros(14)
    
    for i in range(num_iterations):
        cur_cost = cost_gd(coeff,X_train, Y_train)
        print(i, " ",cur_cost)
        coeff = step_gradient(X_train, Y_train, learning_rate, coeff)
    
    return coeff

In [121]:
learning_rate = 0.001
num_iterations = 100

In [122]:
#current_coeff = np.zeros(14)
#new_coeff = step_gradient(X_train,Y_train, learning_rate, current_coeff)
#new_coeff

#cur_cost = cost_gd(new_coeff, X_train, Y_train)
#cur_cost

coeff = gd_runner(X_train, Y_train, learning_rate, num_iterations)
coeff

0   599.122269129
1   376.178266015
2   248.766048881
3   175.946907618
4   134.325802078
5   110.533285541
6   96.9291870783
7   89.147416375
8   84.6929056096
9   82.1398108368
10   80.6733121387
11   79.8277684458
12   79.3370821803
13   79.0491878874
14   78.8771854792
15   78.7714145953
16   78.7034960756
17   78.6572122216
18   78.6232951845
19   78.5964487112
20   78.5736461769
21   78.5531579696
22   78.5339956747
23   78.5155944464
24   78.4976314932
25   78.4799223494
26   78.4623615976
27   78.4448889937
28   78.4274701086
29   78.4100852656
30   78.3927232185
31   78.3753775385
32   78.3580445504
33   78.3407221521
34   78.3234091405
35   78.3061048266
36   78.2888088148
37   78.2715208774
38   78.2542408824
39   78.2369687529
40   78.2197044432
41   78.2024479253
42   78.1851991817
43   78.1679582007
44   78.1507249737
45   78.1334994944
46   78.1162817573
47   78.0990717575
48   78.0818694907
49   78.0646749527
50   78.0474881392
51   78.0303090464
52   78.0131376702
53  

array([-0.16722524,  0.07647999, -0.71707612, -0.33262328, -0.53866432,
       -0.09205105, -0.78849847,  0.06707647, -1.12331396, -1.01951136,
       -0.44285182,  0.32916238, -0.47132571,  0.15380705])

In [123]:
Y_predict = np.dot(X_test,coeff)

In [124]:
Y_predict

array([-6.81016639,  4.10763415,  1.63696642,  5.39555348,  1.42655314,
       -3.30414491,  3.7897    ,  3.84897728,  1.72454772,  3.51632316,
        3.77402946,  0.9826119 ,  3.60029888,  1.83679964, -1.09759652,
        5.25198269,  4.36970021,  3.74822221,  4.96204835,  3.35048323,
        0.91990768, -0.28407973,  0.1253973 ,  3.61305651,  6.04510776,
       -5.5892086 ,  2.37807884,  4.81644483, -0.38820714,  0.37200864,
        1.12242441,  3.54223497,  1.73709157,  3.32385436, -6.68504852,
        2.76152075,  4.59567318,  0.47929365,  4.13725191, -8.40147938,
       -6.46445001,  4.56633972,  5.82575763, -1.98105018, -4.674717  ,
       -7.2042178 ,  1.91677782,  1.60375186,  6.11888963, -6.50877751,
       -5.98281503,  6.26216942, -6.55808755,  1.3214573 ,  0.70823619,
        3.48805494,  1.72457662,  3.71096246,  0.64441111, -6.25094371,
       -7.22457434,  2.03545926,  3.70836207,  3.42557504, -5.98700993,
       -5.75901319,  3.01839002, -6.64996974,  0.96487842, -3.71