In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(2)
b = tf.constant(3)
print(a)
sess = tf.Session()
l = tf.add(a, b)
print(l)
print(sess.run(l))
m = sess.run(a * b)
s = sess.run(a + b)
print(m, s)
sess.run([a * b, a + b])
a

Tensor("Const:0", shape=(), dtype=int32)
Tensor("Add:0", shape=(), dtype=int32)
5
6 5


<tf.Tensor 'Const:0' shape=() dtype=int32>

In [3]:
x = tf.placeholder(tf.int16)
y = tf.placeholder(tf.int16)
add = tf.add(x, y)
sess = tf.Session()
sess.run(add, feed_dict={x:10, y:20})

30

In [4]:
matrix1 = tf.constant([[3,3]])
matrix2 = tf.constant([[3],[3]])
product = tf.matmul(matrix1, matrix2)
with tf.Session() as sess:
    p = sess.run(product)
    print(p)
    

[[18]]


In [5]:
dummyinput = tf.constant([[1, 2], [3, 4]])
dummyweights = tf.constant([[4, 5, 6],[7, 8, 9]])
dummybiases = tf.constant([10,11,12])
product = tf.matmul(dummyinput, dummyweights)
sum1 = tf.add(product, dummybiases)
with tf.Session() as sess:
    p = sess.run(product)
    print(p)
    s = sess.run(sum1)
    print(s)

[[18 21 24]
 [40 47 54]]
[[28 32 36]
 [50 58 66]]


In [6]:
from tensorflow.examples.tutorials.mnist import input_data

Instructions for updating:
Use the retry module or similar alternatives.


In [7]:
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [8]:
mnist.train.images.shape
mnist.train.labels.shape

(55000, 10)

In [9]:
n_hidden_1 = 256
n_hidden_2 = 256
n_input = 784
n_classes = 10

weights = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}

biases = {
    'h1': tf.Variable(tf.random_normal([n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}


In [10]:
def mlp(x, weights, biases):
    layer1 = tf.add(tf.matmul(x, weights['h1']), biases['h1'])
    layer1 = tf.nn.relu(layer1)
    
    layer2 = tf.add(tf.matmul(layer1, weights['h2']), biases['h2'])
    layer2 = tf.nn.relu(layer2)
    
    out_layer = tf.add(tf.matmul(layer2, weights['out']), biases['out'])
    out_layer = tf.nn.sigmoid(out_layer)
    return out_layer

In [11]:
x = tf.placeholder("float", [None, n_input])
y = tf.placeholder("float", [None, n_classes])
pred = mlp(x, weights, biases)
pred

<tf.Tensor 'Sigmoid:0' shape=(?, 10) dtype=float32>

In [12]:
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y))
optimize = tf.train.AdamOptimizer(learning_rate=0.008).minimize(cost)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.



In [13]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [14]:
for i in range(100):
    _ , c = sess.run([optimize, cost], feed_dict={x: mnist.train.images, y:mnist.train.labels})
    print(i, c)

0 2.40852
1 2.3394
2 2.29247
3 2.25245
4 2.20181
5 2.15002
6 2.12325
7 2.10312
8 2.07722
9 2.0472
10 2.01526
11 1.98647
12 1.95515
13 1.92563
14 1.89977
15 1.87557
16 1.8484
17 1.82146
18 1.80046
19 1.78618
20 1.77643
21 1.76823
22 1.75779
23 1.74713
24 1.73791
25 1.73074
26 1.72473
27 1.71913
28 1.71499
29 1.71157
30 1.70899
31 1.70584
32 1.70177
33 1.69766
34 1.6935
35 1.68869
36 1.685
37 1.68229
38 1.6799
39 1.67741
40 1.67535
41 1.67345
42 1.67144
43 1.66964
44 1.66756
45 1.66608
46 1.66437
47 1.66273
48 1.6605
49 1.65893
50 1.65778
51 1.65789
52 1.65843
53 1.65578
54 1.65212
55 1.6492
56 1.64814
57 1.64795
58 1.64722
59 1.64522
60 1.64405
61 1.64348
62 1.64265
63 1.64165
64 1.641
65 1.64086
66 1.64049
67 1.63954
68 1.63824
69 1.63794
70 1.63735
71 1.63761
72 1.63788
73 1.63532
74 1.6333
75 1.63245
76 1.632
77 1.63082
78 1.62975
79 1.62865
80 1.62846
81 1.6285
82 1.62859
83 1.6286
84 1.62854
85 1.62816
86 1.62765
87 1.62661
88 1.62607
89 1.62579
90 1.62546
91 1.62483
92 1.62497
93 

In [15]:
predictions = tf.argmax(pred, 1)
correct_labels = tf.argmax(y, 1)
correct_predictions = tf.equal(predictions, correct_labels)
predictions,correct_predictions  = sess.run([predictions, correct_predictions], feed_dict={x:mnist.test.images,
                                              y:mnist.test.labels})


In [16]:
(correct_predictions == False).sum()

2200

In [17]:
correct_predictions.shape

(10000,)