In [17]:
import numpy as np

In [18]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [19]:
def derivativeSig(sig_out):
    return sig_out*(1 - sig_out)

In [20]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
Y = np.array([[0,0,1,1]]).T

In [44]:
weights = 2 * np.random.random((3,1)) - 1
learning_rate = 0.1
weights

array([[ 0.94886621],
       [ 0.6851859 ],
       [-0.70671683]])

In [45]:
X.shape, weights.shape

((4, 3), (3, 1))

In [65]:
for iter in range(10000):
    output0 = X
    output1 = sig(np.dot(output0, weights))
    first_term = output1 - Y
    second_term = derivativeSig(output1)
    first_two = first_term * second_term
    changes = np.array([[0,0,0.0]])
    for i in range(3):
        for j in range(4):
            changes[0][i] = changes[0][i] + first_two[j][0]*output0[j][i]

    # # net_change = np.dot(output0.T, first_two)
    weights = weights - learning_rate*changes.T
    
output1 = sig(np.dot(X, weights))
weights,output1

(array([[ 8.06015623],
        [-0.21201132],
        [-3.81937647]]), array([[ 0.02147039],
        [ 0.01744012],
        [ 0.98580795],
        [ 0.98251493]]))

In [68]:
weights0 = 2* np.random.random((3,4)) - 1
weights1 = 2* np.random.random((4, 1)) - 1

In [77]:
for iter in range(1000):
    layer0 = X
    layer1 = sig(np.dot(layer0, weights0))
    layer2 = sig(np.dot(layer1, weights1))

    l2_error = layer2 - Y
    l2_delta = l2_error * derivativeSig(layer2)
    net_change2 = np.dot(layer1.T, l2_delta)

    l1_error = l2_delta.dot(weights1.T)
    l1_delta = l1_error  * derivativeSig(layer1)
    net_change1 = np.dot(layer0.T, l1_delta)

    weights0 = weights0 - learning_rate*net_change1
    weights1 = weights1 - learning_rate*net_change2


layer0 = X
layer1 = sig(np.dot(layer0, weights0))
layer2 = sig(np.dot(layer1, weights1))
layer2

array([[ 0.08469061],
       [ 0.07129671],
       [ 0.92969183],
       [ 0.921741  ]])